### ISSUE TITLE
Enhancement: this.getParent() from within controllers

### ISSUE THREAD

**Issue by danjford** [lodestarjs/lodestar-router#18]
It may be useful to be able to access the direct parent from a child controller e.g. in Lodestar-Ractive you could get data from the parent routes controller.

Also if it was set up as `this.getParent()` instead of making it so that all controllers are accessible from all controllers it would avoid accidentally trying to modify a controller that isn't set up, i.e. not in the current hierarchy.

I think it would be important to make it so that only parents can be retrieved and not a sibling or child as this may lead to bad practice and unexpected behaviour. At the same time, I don't think that `getParent()` should have access to the actual `controller()` or events, but is meant more for getting and setting data.

I think that this would be simple to implement, it would just require adding some code to the `resolve()` function so that the parent is stored in `this.getParent()`. This may be easy to do as it may be able to use the pointer used in the recursion.

**Comment by silverlight513** [comment]
:+1:

**Comment by xCausxn** [comment]
:+1: 

and hi jack

**Comment by danjford** [comment]
This has been implemented so that it will get the reference to the parent object. This is then further used in lodestar-ractive to return a specific property i.e. the Ractive View-Model, so that data can be get, set etc.
